#  boot:
#    admin:
#      client:
#        url: http://${eureka.instance.hostname}:8084
#  zipkin:
#    base-url: http://${eureka.instance.hostname}:9411
eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册到eureka，是否要构建集群环境，所以应该开启
    registerWithEureka: false
    #表示是否从eureka获取注册信息，如果是单一节点，不需要同步其他的eureka节点，则可以设置为false，但此处为集群，则应该为true
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://192.168.52.134:${server.port}/eureka/,http://192.168.52.134:${server.port}/eureka/,http://192.168.52.134:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health,info